config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index', to: 'inquiry#index'
  post 'inquiry/confirm', to: 'inquiry#confirm'
  post 'inquiry/thanks', to: 'inquiry#thanks'

  get 'company/index', to: 'company#index'
  get 'company/about', to: 'company#about'
  get 'company/flow', to: 'company#flow'
  get 'company/access', to: 'company#access'
  root 'company#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :name_kana, :tel, :email, :message
  VALID_EMAIL_REGEX = /\A[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*\Z/
  # 電話番号(ハイフンなし10桁or11桁)
  VALID_PHONE_REGEX = /\A\d{10,11}\z/

  validates :name, presence: {message: '名前を入力してください'}
  validates :name_kana, presence: {message: 'ふりがなを入力してください'}
  validates :email, presence: {message: 'メールアドレスを入力してください'}, 
                    format: { with: VALID_EMAIL_REGEX, message: '無効なメールアドレスです' }
  validates :tel, format: { with: VALID_PHONE_REGEX, message: '電話番号はハイフンなし10桁or11桁で入力してください', allow_blank: true  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  def index
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    @inquiry = Inquiry.new
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    # NG。入力画面を再表示
    if @inquiry.invalid?
      render 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:name, :name_kana, :tel, :email, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/company/about.html.haml
.wrapper
  .wrapper__section#introduction
    .wrapper__section__content
      .wrapper__section__content--box
        .wrapper__section__content--box--left
          = image_tag "sisa.jpg", class: "background-half"
        .wrapper__section__content--box--right
          %h3 居宅介護支援事業所とは
          %p ケアマネジャー(介護支援専門員)が介護や介護保険に関する様々な ご相談を承ります。要介護者ご本人やご家族のご要望をもとに、介護保険で受けられるサービスの調整や費用の計算などを当事者に代わって行います。

          %h3 当事業所の特長
          %p 当事業所では「特定事業所加算」を算定しています。特定事業所とは、居宅支援事業所において、専門性の高い人材を確保し、介護度の高い利用者や支援が困難な場合に対しても積極的に提供するといった、質の高い介護サービスを実施している事業所を評価する加算です。 (主任介護支援専門員常勤)

app/views/company/access.html.haml
.wrapper
  .wrapper__section#access
    .wrapper__section__content
      %script{:async => "", :src => "https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_MAP_API_KEY"]}&callback=initMap"}
      :javascript
        var map;
          var marker;
          var geocoder;
          function initMap() {
            geocoder = new google.maps.Geocoder();
            geocoder.geocode({
            'address': '名護市宇茂佐の森4-3-2' //住所
            }, function(results, status) { 
              if (status === google.maps.GeocoderStatus.OK) {
              map = new google.maps.Map(document.getElementById('gmap'), {
                center: results[0].geometry.location,
                zoom: 17 //ズーム
            });
            marker = new google.maps.Marker({
            position: results[0].geometry.location,
            map: map
            });
            infoWindow = new google.maps.InfoWindow({
            content: '<h4>ツールチップのタイトル</h4>'
            });
            marker.addListener('click', function() {
              infoWindow.open(map, marker); 
            });
            } else { 
              alert(status);
            }
          });
        }
      #gmap
      .wrapper__section__content--map-text

        %h3 〒905-0009
        %h3 名護市宇茂佐の森4-3-2
        %h3 トーマス宇茂佐の森305号 
        %h3 電話:0980-43-6717　Fax:0980-43-6718
        %h3 受付時間 月~土、午前 9 時~午後6時まで 
        %h3 (日・祝日・年末年始はお休みです)

      .wrapper__section__content--text-upper
        %h3 介護の悩みや困り事がありましたらいつでもご相談ください
        %h2 相談無料
        %br 
        %h3 通常の提供地域 名護市・本部町・今帰仁村
        %h3 ※その他地域の方もご相談ください
        %br
      .wrapper__section__content--text-bottom
        %h3 お気軽にお電話ください
        %h2 0980-43-6717
      .wrapper__section__content--image
        = image_tag "goricho.jpg", class: "background-half--bottom"
        = image_tag "sisa2.jpg", class: "background-half--bottom"

app/views/company/flow.html.haml
.wrapper
  .wrapper__section#flow
    = image_tag "flow-image.jpg", class: "background-flow"

app/views/company/index.html.haml
.wrapper
  %p#page-top
    = link_to "PAGE TOP", ""
  .wrapper__section#top
    = image_tag "gazyumaru1.jpg",class: "background"
    = image_tag "couple.jpg", class: "background"
    = image_tag "couple2.jpg",class: "background"
  .wrapper__section#main
    .wrapper__section__top
      %h4 沖縄県指定事業者番号: 4770900902
    .wrapper__section__title
      = image_tag "logo.png", size: "150×200", class: "wrapper__section__title--image"
      .wrapper__section__title--text
        %h3 居宅介護支援事業所
        %h2 がゆまーる
    .wrapper__section__text
      %h3 「がゆまーる」は名護市のシンボル「がじゅまるの木」と、沖縄の方言で助け合いを意味 する「ゆいまーる」を組み合わせて名付けました。
      %br
      %h3 がじゅまるの木のように名護市に根付き、ゆいまーる精神で地域一丸となって高齢者を支えていけるような事業所でありたいとの思いが込めれられています。

  .wrapper__section
    .wrapper__section__content
      .wrapper__section__content--box
        .wrapper__section__content--box--left
          %h3 介護保険申請代行
          %h3 ケアプラン作成
          %h3 介護サービス調整
          %h3 介護サービス管理
          %h4 介護の悩みや困り事がありましたら
          %h4 いつでもご相談ください
          .wrapper__section__content--box--left__image
            = image_tag "logo2.png"
        .wrapper__section__content--box--right--image
          = image_tag "gazyumaru2.jpg", class: "background-half"
          = image_tag "bridge.jpg", class: "background-half"

  .wrapper__section#introduction#hide
    .wrapper__section__content
      .wrapper__section__content--box

        .wrapper__section__content--box--right
          %h3 居宅介護支援事業所とは
          %p ケアマネジャー(介護支援専門員)が介護や介護保険に関する様々な ご相談を承ります。要介護者ご本人やご家族のご要望をもとに、介護保険で受けられるサービスの調整や費用の計算などを当事者に代わって行います。

          %h3 当事業所の特長
          %p 当事業所では「特定事業所加算」を算定しています。特定事業所とは、居宅支援事業所において、専門性の高い人材を確保し、介護度の高い利用者や支援が困難な場合に対しても積極的に提供するといった、質の高い介護サービスを実施している事業所を評価する加算です。 (主任介護支援専門員常勤)

  .wrapper__section#flow#hide
    = image_tag "flow-image-s1.png", class: "background-flow"
    = image_tag "flow-image-s2.png", class: "background-flow"

  .wrapper__section#access#hide
    .wrapper__section__content
      %script{:async => "", :src => "https://maps.googleapis.com/maps/api/js?key=#{ENV["GOOGLE_MAP_API_KEY"]}&callback=initMap"}
      :javascript
        var map;
          var marker;
          var geocoder;
          function initMap() {
            geocoder = new google.maps.Geocoder();
            geocoder.geocode({
            'address': '名護市宇茂佐の森4-3-2' //住所
            }, function(results, status) { 
              if (status === google.maps.GeocoderStatus.OK) {
              map = new google.maps.Map(document.getElementById('gmap'), {
                center: results[0].geometry.location,
                zoom: 17 //ズーム
            });
            marker = new google.maps.Marker({
            position: results[0].geometry.location,
            map: map
            });
            infoWindow = new google.maps.InfoWindow({
            content: '<h4>ツールチップのタイトル</h4>'
            });
            marker.addListener('click', function() {
              infoWindow.open(map, marker); 
            });
            } else { 
              alert(status);
            }
          });
        }
      .wrapper__section__content--map-text

        %h3 〒905-0009
        %h3 名護市宇茂佐の森4-3-2
        %h3 トーマス宇茂佐の森305号 
        %h3 電話:0980-43-6717　
        %h3 Fax:0980-43-6718
        %br
        %h3 受付時間 月~土、
        %h3 午前 9時~午後6時まで 
        %h3 (日・祝日・年末年始はお休みです)

      .wrapper__section__content--text-upper
        %h3 介護の悩みや困り事がありましたら
        %h3 いつでもご相談ください
        %h2 相談無料
        %br 
        %h3 通常の提供地域 
        %h3 名護市・本部町・今帰仁村
        %h3 ※その他地域の方もご相談ください
        %br
      .wrapper__section__content--text-bottom
        %h3 お気軽にお電話ください
        .tel
          = link_to "0980-43-6717", "tel:0980-43-6717"
        %br
        %br
        %h2 メールでのご相談も承ります
        .tel
          = link_to inquiry_index_path do
            =fa_icon("envelope",text: "お問い合わせはこちら")
      .wrapper__section__content--image
        = image_tag "goricho.jpg", class: "background-half--bottom"
        = image_tag "sisa2.jpg", class: "background-half--bottom"
      #gmap

app/views/inquiry/confirm.html.haml
.newWrap
  .newTitle
    %h1 お問い合わせ:確認
  .newContent
    = form_for(@inquiry,  url: {controller: 'inquiry', action: 'thanks'} ) do |f|
      .row
        .title
          お名前
        .box
          = f.hidden_field :name
          = @inquiry.name
        .title
          ふりがな
        .box
          = f.hidden_field :name_kana
          = @inquiry.name_kana
        .title
          お電話番号
        .box
          = f.hidden_field :tel
          = @inquiry.tel
        .title
          メールアドレス
        .box
          = f.hidden_field :email
          = @inquiry.email
        .title お問い合わせ内容
        .box.textarea
          = f.hidden_field :message
          = @inquiry.message
      = f.submit '送信する', class: 'btn'

app/views/inquiry/index.html.haml
- @page_title = 'お問い合わせ'
.newWrap
  .newTitle
    %h1 お問い合わせ
  .newContent
    = form_for(@inquiry,  url: {controller: 'inquiry', action: 'confirm'} ) do |f|
      - if @inquiry.errors.any?
        .alert{:role => "alert"}
          %strong 入力内容にエラーがあります
          %ul
            - @inquiry.errors.each do |attr, msg|
              %li= msg
      .row
        .title
          お名前
          %span.text-danger （必須）
        .box
          = f.text_field :name, class: 'form', placeholder: '山田 太郎'
        .title
          フリガナ
          %span.text-danger （必須）
        .box
          = f.text_field :name_kana, class: 'form', placeholder: 'ヤマダ タロウ'
        .title
          お電話番号(ハイフンなし)
        .box
          = f.text_field :tel, class: 'form'
        .title
          メールアドレス
          %span.text-danger （必須）
        .box
          = f.text_field :email, class: 'form'
        .title お問い合わせ内容
        .box.textarea
          = f.text_area :message, class: 'form', rows: '6'
      = f.submit '確認', class: 'btn'
      %p.page-top
        = link_to root_path do
          トップページへ戻る

app/views/inquiry/thanks.html.haml
.newWrap
  .newTitle
    %h1 お問い合わせ:送信完了
  .newContent
    %p ※このメールはシステムからの自動返信です
    %br
    ="#{@inquiry.name}　様"
    %p お問い合わせありがとうございます
    %p 以下の内容でお問い合わせを受け付けいたしました
    %p 改めて、担当よりご連絡をさせていただきます
    %br
    ━━━━━━□■□　お問い合わせ内容　□■□━━━━━━
    %br
    お名前：
    =@inquiry.name
    %br
    E-Mail：
    =@inquiry.email
    %br
    電話番号：
    =@inquiry.tel
    %br
    お問い合せ日時：
    =Time.zone.now.to_s(:published_on)
    %br
    お問い合わせ内容：
    =@inquiry.message
    %br
    ━━━━━━━━━━━━━━━━━━━━━━━━━━

app/views/layouts/_footer.html.haml
%footer
  .wrapper-footer
    .wrapper-footer__content
      .wrapper-footer__content__text
        %ul
          %li 居宅介護支援事業所　がゆまーる
          %li （株式会社　アウェアネス）
          %li Copyright (C) AWARENESS Co,.Ltd. All right reserved.
          

app/views/layouts/_header.html.haml
%header
  .wrapper-header
    .wrapper-header__link
      %ul
        %li
          = link_to root_path do
            トップ
        %li
          = link_to company_about_path do
            当事業所について
        %li
          = link_to company_flow_path do
            ご利用の流れ
        %li
          = link_to company_access_path do
            アクセス
        %li
          = link_to inquiry_index_path do
            お問い合わせ
    .wrapper-header__tel
      %p お問い合わせはこちらへ
      .wrapper-header__tel__bottom
        = link_to "0980-43-6717", "tel:0980-43-6717"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title がゆまーる
    = csrf_meta_tags
    %link{ rel: "stylesheet", href: "https://use.fontawesome.com/releases/v5.11.2/css/all.css"}
    %script{ src: "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %script{ type: "text/javascript", src: "/assets/slick.min.js"}
    %meta{:content => "UNOx7suJS91w_PhH50XTpbjzK4_lFUeWWoxR2d--wUI", :name => "google-site-verification"}/
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
  %body
    = render "layouts/header"
    = yield
  = render "layouts/footer"